# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  # name of the builder
  route_func_gen:
    # library URI containing the builder - maps to `lib/member_count_library_generator.dart`
    import: "package:get_router/builder.dart"
    # Name of the function in the above library to call.
    builder_factories: ["routeFuncGen"]
    # The mapping from the source extension to the generated file extension
    build_extensions: {".dart": [".r.dart"]}
    # Will automatically run on any package that depends on it
    auto_apply: dependents
    # Generate the output directly into the package, not to a hidden cache dir
    build_to: source